const Data = [
  {
    id: 1,
    nombre: "TAZA MAGICA PERZONALIZADA",
    descripcion: "Taza blanca de ceramica, apta para microondas.",
    precio: 500,
    stock: 15,
    imagen: "../../Multimedia/Fotos/productotaza.jpg",
    category: "Imprenta",
  },
  {
    id: 2,
    nombre: "RESMA A4 AUTOR",
    descripcion: "500 hojas de 210 x 297 mm blancas listas para usar.",
    precio: 650,
    stock: 17,
    imagen: "../../Multimedia/Fotos/productoresmaa4.jpg",
    category: "Imprenta",
  },
  {
    id: 3,
    nombre: "RESMA A3 AUTOR",
    descripcion: "250 hojas de 297 x 420 mm listas para usar.",
    precio: 900,
    stock: 12,
    imagen: "../../Multimedia/Fotos/productoresmaa3.jpg",
    category: "Imprenta",
  },
  {
    id: 4,
    nombre: "ACEITE DE COCO",
    descripcion:
      "Es un aceite neutro, sin aroma y sin sabor extraido a 24° de temperatura.",
    precio: 750,
    stock: 19,
    imagen: "../../Multimedia/Fotos/productococo.jpg",
    category: "Almacen",
  },
  {
    id: 5,
    nombre: "DULCE DE LECHE CHICO",
    descripcion: "El mejor dulce de leche regional para tus postres.",
    precio: 340,
    stock: 18,
    imagen: "../../Multimedia/Fotos/productodulcechico.jpg",
    category: "Almacen",
  },
  {
    id: 6,
    nombre: "DULCE DE LECHE GRANDE",
    descripcion: "El mejor dulce regional ahora mas grande",
    precio: 790,
    stock: 10,
    imagen: "../../Multimedia/Fotos/productodulcegrande.jpg",
    category: "Almacen",
  },
  {
    id: 7,
    nombre: "SELLO AUTOMATICO",
    descripcion: "Perzonaliza tu sello con hasta 4 lineas.",
    precio: 450,
    stock: 11,
    imagen: "../../Multimedia/Fotos/productosello.jpg",
    category: "Imprenta",
  },
  {
    id: 8,
    nombre: "YERBA DON ARREGUI",
    descripcion: "La yerba Cordobesa.",
    precio: 350,
    stock: 12,
    imagen: "../../Multimedia/Fotos/productoyerba.jpg",
    category: "Almacen",
  },
  {
    id: 9,
    nombre: "YERBA KALENA",
    descripcion: "La Yerba con palo mas rica.",
    precio: 450,
    stock: 9,
    imagen: "../../Multimedia/Fotos/productoyerba2.jpg",
    category: "Almacen",
  },
];

export default Data;
